version: 2.1

executors:
  nodejs_v10:
    resource_class: small
    docker:
      - image: circleci/node:10

commands:
  setup_git:
    description: Setup swybot git username + email
    steps:
      - run:
          name: Setup git
          command: |
            git config --global user.name SwyBot
            git config --global user.email SwyBot@users.noreply.github.com
jobs:
  test:
    executor: nodejs_v10
    steps:
      - checkout
      - run:
          name: Install
          command: |
            npm ci
      - run:
          name: Bootstrap
          command: |
            npx lerna bootstrap
      - run:
          name: Run lint
          command: |
            npm run lint -s
      - run:
          name: Run unit tests
          command: |
            npm run unit -s

  release:
    executor: nodejs_v10
    steps:
      - checkout
      - setup_git
      - run:
          name: Install
          command: |
            npm ci
      - run:
          name: Configure npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run:
          name: Publish modules
          command: |
            npx lerna publish

workflows:
  version: 2
  build_test_release:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - release:
          filters:
            branches:
              only:
                - master
