version: 2.1

executors:
  nodejs_v10:
    resource_class: small
    docker:
      - image: circleci/node:10

commands:
  setup_git:
    description: Setup swybot git username + email
    steps:
      - run:
          name: Setup git
          command: |
            git config --global user.name SwyBot
            git config --global user.email SwyBot@users.noreply.github.com
  setup_npm:
    description: Setup npm for publishing
    steps:
      - run:
          name: Setup npm
          command: |
            if [ -f ~/.npmrc ]; then
              rm ~/.npmrc
            fi
            touch ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ~/.npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
jobs:
  test:
    executor: nodejs_v10
    steps:
      - checkout
      - run:
          name: Install
          command: |
            npm ci
      - run:
          name: Bootstrap
          command: |
            npx lerna bootstrap
      - run:
          name: Run lint
          command: |
            npm run lint -s
      - run:
          name: Run unit tests
          command: |
            npm run unit -s

  release:
    executor: nodejs_v10
    steps:
      - checkout
      - setup_git
      - setup_npm
      - run:
          name: Install
          command: |
            npm ci
      - run:
          name: Create version
          command: |
            npx lerna version
      - run:
          name: Publish modules on GitHub
          command: |
            npx lerna publish from-package --registry https://npm.pkg.github.com
      - run:
          name: Publish modules on npm
          command: |
            npx lerna publish from-package --registry https://registry.npmjs.org

workflows:
  version: 2
  build_test_release:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - release:
          filters:
            branches:
              only:
                - master
