name: release

on:
  push:
    branches:
      - master*
    tags-ignore:
      - '*'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Configure git
        run: |
          git config --global user.name SwyBot
          git config --global user.email SwyBot@users.noreply.github.com
      - name: Build
        run: |
          npm ci
      - name: Create release
        run: |
          npx lerna version
  publish_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
      - name: Build
        run: |
          npm ci
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx lerna publish --no-push --no-git-tag-version --registry https://npm.pkg.github.com
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Build
        run: |
          npm ci
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx lerna publish --no-push --no-git-tag-version --registry https://registry.npmjs.org
