name: renovate

on:
  pull_request:
    paths:
      - '.github/workflows/renovate.yml'
      - 'renovate.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: rinchsan/renovate-config-validator@v0.0.12
        name: Validate config
        with:
          pattern: 'renovate.json'
