name: test

on:
  pull_request:
    branches:
      - master*

jobs:
  modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
            node-version: '14'
      - name: Build
        run: |
            npm ci
            npx lerna bootstrap
      - name: Lint
        run: |
            npm run lint -s
      - name: Unit
        run: |
            npm run unit -s
      - name: Run cli
        run: |
          npm run cli help
