name: test

on:
  pull_request:
    branches:
      - master*

jobs:
  modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Build
        run: |
            npm ci
      - name: Lint
        run: |
            npm run lint -s
      - name: Unit
        run: |
            npm run unit -s
      - name: Run cli
        run: |
          npm run cli help
